version: "3"

networks:
  app-tier:
    driver: bridge

services:
  server:
    build:
      dockerfile: Dockerfile
    networks:
        - my-net
        - bridge
    expose:
      - 5000
    environment:
      - PORT=5000
      - NODE_ENV=development


    